### ISSUE TITLE
Start datetime display doesn't match NUNIT start-time

### ISSUE THREAD

**Issue by msscribner** [GHPReporter/Ghpr.NUnit#68]
**Describe the bug**
Looking at the NUNIT log, the tests ran from: 
   start-time="2019-10-**07 02:51:57**Z" 
   end-time="2019-10-07 07:10:49Z" 
   duration="15532.193087"

But the report is displaying:
   Start datetime: 2019-10-**06 22:51:58**
   Finish datetime: 2019-10-07 03:10:49
   Duration: 04:18:51.00

Start datetime has the wrong day and time!

![image](https://user-images.githubusercontent.com/45525002/67519893-cb10e780-f675-11e9-8a5a-470ea469bd03.png)

![image](https://user-images.githubusercontent.com/45525002/67519922-db28c700-f675-11e9-92ce-38a07803776d.png)

**Expected behavior**
Was expecting to see something along the lines of:
   Start datetime: 2019-10-07 02:51:57
   Finish datetime: 2019-10-07 07:10:49

The NuGet packages I'm using are the latest:

![image](https://user-images.githubusercontent.com/45525002/67520672-445d0a00-f677-11e9-8e13-94c65ce1cb2b.png)

**Comment by elv1s42** [comment]
Hi @msscribner !

In Ghpr.NUnit there is a different approach to get test run start and end time. That's because in NUnit both `start-time` and `end-time` for each run and for each test have format `yyyy-MM-dd HH:mm:ss`.

But the bug may be related to timezone differences as NUnit is using UTC DateTime. 

Can you please tell me what was the local timezone on the machine where the tests were running?
I can assume that you have ~4 hour difference with UTC time. If so then the bug should be easy to fix.

Thank you

**Comment by msscribner** [comment]
Report is generated in Eastern Time Zone.... but I think the 4 hour difference is probably related to UTC time as you pointed out.  I'll 'Close' issue.

**Comment by elv1s42** [comment]
Released in v0.9.10
