### ISSUE TITLE
Screenshot fail when I set up the "TakeScreenshotAfterFail" parameter to True

### ISSUE THREAD

**Issue by yfrindel** [GHPReporter/Ghpr.NUnit#7]
Hi elv1s42,

Thank you for this good report.
I don't know why, but when I set up the "TakeScreenshotAfterFail" parameter to True, the tests failed don't appear in the report.
Is it a bug ?

Thank you to help me.

Yannick

**Comment by elv1s42** [comment]
Hello. 
Right now it does not work with Jenkins, it works only for running tests locally on your machine.

I will investigate this issue.

Thanks for this issue

**Comment by elv1s42** [comment]
Hi @yfrindel !
Please let me know if this issue has gone with latest Ghpr.Core, Ghpr.NUnit (both v0.4.3) and NUnit.Console (v3.6). Please note, that now there is no need to edit `nunit.console.exe.config` file, because all settings are passed via .json settings file. 
If you are going to take screenshots inside yout tests, then make sure that you have the same `Ghpr.NUnit.Settings.json` file inside your C# project and inside NUnit.Console addins folder.

Also, take a look at [How to work with screenshots section.](https://github.com/GHPReporter/Ghpr.NUnit#how-to-work-with-screenshots)

**Comment by elv1s42** [comment]
Issue fixed in v0.4.3

**Comment by yfrindel** [comment]
Hi,
not tested yet...I'm busy with other things, but I will take a look.
Yannick 

    Le Mardi 17 janvier 2017 17h07, Evgeniy Kosjakov <notifications@github.com> a écrit :
 

 Hi @yfrindel !
Please let me know if this issue has gone with latest Ghpr.Core, Ghpr.NUnit (both v0.4.3) and NUnit.Console (v3.6). Please note, that now there is no need to edit nunit.console.exe.config file, because all settings are passed via .json settings file.
If you are going to take screenshots inside yout tests, then make sure that you have the same Ghpr.NUnit.Settings.json file inside your C# project and inside NUnit.Console addins folder.Also, take a look at How to work with screenshots section.—
